config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
      @list = List.find(params[:list_id])
      @bookmark = Bookmark.new(bookmark_params)
      @bookmark.list = @list
      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), notice: "Bookmark has been destroyed", status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
      @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  def destroy
    @list= List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: "List has been destroyed", status: :see_other
  end


  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      # @bookmark = Bookmark.new
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

 <%# NAVBAR %>

      <div class="navbar navbar-expand-sm static-top navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to "#", class: "navbar-brand" do %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <%# if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "My lists", lists_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Create new list", new_list_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Action", "#", class: "dropdown-item" %>
                  <%= link_to "Another action", "#", class: "dropdown-item" %>
                  <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
                </div>
              </li>
            <%# else %>
              <!--li class="nav-item"-->
                <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
              <!--/li-->
            <%# end %>
          </ul>
        </div>
      </div>
    </div>

 <%# NAVBAR %>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1543536448-1e76fc2795bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1739&q=80);">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>


<div class="container">
  <div class="top">
      <h2>My lists</h2>
      <h2 class="btn btn-flat"><%= link_to "Create a movie list", new_list_path %></h2>
    </div>
</div>

<div class="container">
    <div class="row">
        <% @lists.each do |list| %>
          <div class="card-category col-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 200, crop: :fill %>')"> <%= link_to list.name, list_path(list)%>
            <%=link_to "🗑️", list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
            <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<h1>Create new list</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create list" %>
<% end %>

app/views/lists/show.html.erb
<div class="header my-5">
  <h2><%= @list.name %></h2>
</div>


<ul>
 <% @list.movies.each do | movie | %></h3>
  <li> <%= movie.title %>
   <%= image_tag movie.poster_url, width: 200 %>
       </li>
  <% movie.bookmarks.each do|bookmark| %>
  <li> <%= bookmark.comment %></li>
  <li> <%= bookmark.movie.overview %></li>
  <%=link_to "delete bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <%end %>
<%end %>
</ul>

<h3 class="btn btn-secondary"><%= link_to "All lists", lists_path %></h3>
<h3 class="btn btn-primary"><%= link_to "Create a bookmark", new_list_bookmark_path(@list) %></h3>

<% if @list.reviews.empty? %>
<h1>Leave a review about <%= @list.name %> </h1>
<% end  %>

<% @list.reviews.each do |review| %>
  <ul>
    <li><%= review.comment %></li>
    <li><%= "⭐️" * review.rating %></li>
  </ul>
  <h4 class="btn btn-warning"><%= link_to "Delete this review", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></h4>
<% end%>

<h1> Add your review below! </h1>
<%= simple_form_for [@list, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>